name: Taipower Scraper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run scraper
      env:
        PCLOUD_EMAIL: ${{ secrets.PCLOUD_EMAIL }}
        PCLOUD_PASSWORD: ${{ secrets.PCLOUD_PASSWORD }}
      run: python main.py
